version: "3.7"

services:
  team-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/teamfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev
    environment:
      - TZ=Asia/Seoul

  elasticsearch:
    build:
      context: ./elk/elasticsearch
      dockerfile: Dockerfile.elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200

  logstash:
    image: logstash:7.17.0
    volumes:
      - ./elk/logstash/logstash.prod.conf:/usr/share/logstash/pipeline/logstash.prod.conf
      - ./elk/logstash/mysql-connector-java-8.0.28.jar:/usr/share/logstash/mysql-connector-java-8.0.28.jar
      - ./elk/elasticsearch/config-elasticsearch.json:/usr/share/logstash/config-elasticsearch.json
      - ./elk/elasticsearch/stopword.txt:/usr/share/logstash/stopword.txt
