version: "3.7"

services:
  team-backend:
    image: asia.gcr.io/galvanic-cirrus-360400/team-backend:0.95
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.prod

  # elasticsearch:
  #   build:
  #     context: ./elk/elasticsearch
  #     dockerfile: Dockerfile.elasticsearch

  #   environment:
  #     discovery.type: single-node
  #     TZ: Asia/Seoul
  #   ports:
  #     - 9200:9200

  # logstash:
  #   image: logstash:7.16.2
  #   volumes:
  #     - ./elk/logstash/logstash.prod.conf:/usr/share/logstash/pipeline/logstash.prod.conf
  #     - ./elk/logstash/mysql-connector-java-8.0.28.jar:/usr/share/logstash/mysql-connector-java-8.0.28.jar
  #     - ./elk/elasticsearch/config-elasticsearch.json:/usr/share/logstash/config-elasticsearch.json
  #   environment:
  #     TZ: Asia/Seoul
